// apps/docs/src/components/bottom-cta.tsx
import { Link } from "react-router";

export function BottomCta() {
	return (
		<section className="relative w-full border-t border-dashed border-zinc-300/90 dark:border-zinc-800/80 bg-white dark:bg-black py-20 text-zinc-900 dark:text-white sm:py-28 transition-colors duration-300">
			<div className="mx-auto max-w-5xl px-4 text-center sm:px-6 lg:px-8">
				<span className="inline-flex rounded border border-dashed border-zinc-300 dark:border-zinc-700 bg-zinc-100 dark:bg-zinc-950 px-3 py-1 font-mono text-xs text-zinc-700 dark:text-zinc-300">
					MIT Licensed · 100% Open Source
				</span>

				<h2 className="mt-6 text-3xl font-bold tracking-tight text-zinc-900 dark:text-white sm:text-5xl">
					One command. Your agent never forgets.
				</h2>

				<p className="mx-auto mt-4 max-w-xl text-base text-zinc-600 dark:text-zinc-400">
					Get started in under 2 minutes. Install the CLI or import the SDK
					directly into your TypeScript project.
				</p>

				<div className="mt-8 flex flex-wrap items-center justify-center gap-4">
					<Link
						to="/docs/introduction"
						className="inline-flex h-10 items-center justify-center rounded bg-zinc-900 text-white hover:bg-zinc-700 dark:bg-white dark:text-black dark:hover:bg-zinc-200 px-5 text-sm font-medium transition-colors shadow-sm"
					>
						Get Started →
					</Link>
					<a
						href="https://github.com/memo-fs/memofs"
						target="_blank"
						rel="noopener noreferrer"
						className="inline-flex h-10 items-center justify-center rounded border border-zinc-300 bg-zinc-100 text-zinc-800 hover:bg-zinc-200 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300 dark:hover:bg-zinc-800 dark:hover:text-white px-5 text-sm font-medium transition-colors"
					>
						Star on GitHub
					</a>
					<a
						href="https://memofs.dev"
						target="_blank"
						rel="noopener noreferrer"
						className="inline-flex h-10 items-center justify-center rounded border border-cyan-600/40 bg-cyan-50 hover:bg-cyan-100 dark:border-zinc-800 dark:bg-zinc-950 dark:text-cyan-400 dark:hover:border-cyan-500/50 dark:hover:bg-cyan-950/20 px-5 text-sm font-medium transition-colors"
					>
						MemoFS Cloud
					</a>
				</div>
			</div>
		</section>
	);
}

// apps/docs/.vitepress/theme/components/BottomCta.vue
<script setup lang="ts">
import CopyButton from "./CopyButton.vue";
</script>

<template>
  <section id="get-started" class="bottom-cta-section tek-reveal">
    <div class="container">
      <div class="cta-panel">
        <p class="oss-badge">MIT Licensed · 100% open source</p>
        <h2 class="cta-headline">One command. Your agent never forgets.</h2>
        <div class="code-snippet large code-snippet-with-copy">
          <code>npx @memofs/cli init</code>
          <CopyButton text="npx @memofs/cli init" class="code-snippet-copy" />
        </div>
        <div class="cta-buttons">
          <a href="/introduction" class="cta-button primary">Read the Quick Start →</a>
          <a href="https://memofs.dev" class="cta-button secondary" target="_blank" rel="noopener">
            Explore MemoFS Cloud →
          </a>
        </div>
        <a
          href="https://github.com/memo-fs/memofs"
          class="bottom-cta-link"
          target="_blank"
          rel="noopener noreferrer"
        >
          View on GitHub
        </a>
      </div>
    </div>
  </section>
</template>

<style scoped>
.container {
  max-width: var(--tek-container-narrow);
  margin: 0 auto;
  padding: 0 24px;
}

.bottom-cta-section {
  padding: var(--tek-section-pad) 0;
  border-top: 1px solid var(--vp-c-divider);
}

.cta-panel {
  position: relative;
  max-width: 820px;
  margin: 0 auto;
  padding: 64px 40px;
  text-align: center;
  background: var(--vp-c-bg-soft);
  border: 1px solid var(--vp-c-divider);
  border-radius: var(--tek-radius);
  box-shadow: var(--tek-shadow-md);
}

.oss-badge {
  font-family: var(--vp-font-family-mono);
  font-size: 13px;
  color: var(--vp-c-text-2);
  margin: 0 0 16px;
}

.cta-headline {
  font-family: var(--vp-font-family-display);
  font-weight: 700;
  font-size: clamp(28px, 4vw, 40px);
  line-height: 1.12;
  letter-spacing: -0.02em;
  color: var(--vp-c-text-1);
  margin: 0 0 28px;
}

.code-snippet {
  background: var(--vp-code-block-bg);
  border: 1px solid var(--vp-c-border);
  border-radius: var(--tek-radius);
  padding: 12px 16px;
  font-family: var(--vp-font-family-mono);
  font-size: 13.5px;
  overflow-x: auto;
  line-height: 1.6;
  color: var(--vp-code-color);
}

.code-snippet.large {
  display: inline-flex;
  align-items: center;
  padding: 16px 20px;
  font-size: 16px;
  margin-bottom: 28px;
  padding-right: 48px;
  position: relative;
}

.code-snippet-copy {
  position: absolute;
  top: 50%;
  right: 8px;
  transform: translateY(-50%);
}

.cta-buttons {
  display: flex;
  justify-content: center;
  gap: 16px;
  margin-bottom: 28px;
  flex-wrap: wrap;
}

.cta-button {
  display: inline-block;
  padding: 12px 26px;
  border-radius: var(--tek-radius);
  font-family: var(--vp-font-family-display);
  font-size: 15px;
  font-weight: 600;
  text-decoration: none;
  transition: transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease, color 0.2s ease;
}

.cta-button.primary {
  background: var(--tek-c-cyan);
  color: #fff;
  box-shadow: var(--tek-shadow-sm);
}

.cta-button.primary:hover {
  background: var(--vp-c-brand-2);
  transform: translateY(-2px);
  box-shadow: var(--tek-shadow-glow);
}

.cta-button.secondary {
  background: transparent;
  color: var(--vp-c-text-1);
  border: 1px solid var(--vp-c-border);
}

.cta-button.secondary:hover {
  border-color: var(--tek-c-cyan);
  color: var(--tek-c-cyan);
  transform: translateY(-2px);
}

.bottom-cta-link {
  font-family: var(--vp-font-family-display);
  font-size: 15px;
  font-weight: 600;
  color: var(--vp-c-text-2);
  text-decoration: none;
}

.bottom-cta-link:hover { color: var(--tek-c-cyan); }

@media (max-width: 860px) {
  .cta-panel {
    padding: 48px 24px;
  }
}

@media (max-width: 640px) {
  .cta-buttons {
    flex-direction: column;
    align-items: stretch;
  }

  .cta-button {
    text-align: center;
  }
}
</style>
