// apps/docs/src/components/newsletter-signup.tsx
/** Newsletter signup UI backed by the Cloudflare Pages `/subscribe` Function. */

import { type FormEvent, useState } from "react";

/** Presentation variants for a newsletter signup form. */
interface NewsletterSignupProps {
	variant?: "strip" | "card";
	title?: string;
	description?: string;
	className?: string;
}

/** Response body returned by the Pages Function. */
interface SignupResponse {
	ok?: boolean;
	error?: string;
}

/** Renders a reusable signup form that posts directly to the Pages Function. */
export function NewsletterSignup({
	variant = "strip",
	title = "Stay in the loop",
	description = "New releases, SDK updates, and architecture deep dives straight to your inbox.",
	className = "",
}: NewsletterSignupProps) {
	const [isSubmitting, setIsSubmitting] = useState(false);
	const [isSuccess, setIsSuccess] = useState(false);
	const [errorMessage, setErrorMessage] = useState<string>();

	async function handleSubmit(event: FormEvent<HTMLFormElement>) {
		event.preventDefault();
		setIsSubmitting(true);
		setErrorMessage(undefined);

		try {
			const response = await fetch("/subscribe", {
				method: "POST",
				body: new FormData(event.currentTarget),
			});
			const payload = (await response.json()) as SignupResponse;

			if (!response.ok || !payload.ok) {
				setErrorMessage(
					payload.error ?? "Subscription failed. Please try again.",
				);
				return;
			}

			setIsSuccess(true);
		} catch {
			setErrorMessage("Subscription failed. Please try again.");
		} finally {
			setIsSubmitting(false);
		}
	}

	const form = (
		<form
			method="post"
			action="/subscribe"
			onSubmit={handleSubmit}
			className={
				variant === "strip"
					? "flex flex-col gap-2 sm:flex-row sm:items-center"
					: "flex flex-col gap-2.5 sm:flex-row sm:items-center"
			}
		>
			<input
				type="email"
				name="email"
				placeholder="you@domain.com"
				autoComplete="email"
				aria-label="Email address"
				disabled={isSubmitting}
				required
				className={
					variant === "strip"
						? "h-9 w-full sm:flex-1 rounded border border-dashed border-zinc-300 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-900/90 px-3 font-mono text-xs text-zinc-900 dark:text-white placeholder-zinc-400 focus:border-zinc-500 focus:outline-none dark:focus:border-zinc-400 transition-colors disabled:opacity-60"
						: "h-10 w-full sm:flex-1 rounded border border-dashed border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900/90 px-3.5 font-mono text-xs sm:text-sm text-zinc-900 dark:text-white placeholder-zinc-400 focus:border-zinc-500 focus:outline-none dark:focus:border-zinc-400 transition-colors disabled:opacity-60"
				}
			/>
			<button
				type="submit"
				disabled={isSubmitting}
				className={
					variant === "strip"
						? "inline-flex h-9 shrink-0 items-center justify-center rounded bg-zinc-900 px-4 font-mono text-xs font-medium text-white transition-colors hover:bg-zinc-700 dark:bg-white dark:text-black dark:hover:bg-zinc-200 disabled:opacity-60 cursor-pointer"
						: "inline-flex h-10 shrink-0 items-center justify-center rounded bg-zinc-900 px-5 font-mono text-xs sm:text-sm font-medium text-white transition-colors hover:bg-zinc-700 dark:bg-white dark:text-black dark:hover:bg-zinc-200 disabled:opacity-60 cursor-pointer"
				}
			>
				{isSubmitting ? "Subscribing…" : "Subscribe"}
			</button>
		</form>
	);

	const result = isSuccess ? (
		<div className="flex items-center gap-2 rounded border border-emerald-500/30 bg-emerald-50/60 px-3.5 py-2 text-xs font-mono text-emerald-700 dark:bg-emerald-950/20 dark:text-emerald-300">
			<span>✓</span>
			<span>You&apos;re in. Welcome email on its way.</span>
		</div>
	) : (
		form
	);

	if (variant === "strip") {
		return (
			<div
				className={`w-full border-b border-dashed border-zinc-200 pb-10 dark:border-zinc-800/80 ${className}`}
			>
				<div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between">
					<div className="max-w-xl">
						<div className="flex items-center gap-2">
							<span className="inline-block h-1.5 w-1.5 rounded-full bg-emerald-500" />
							<span className="font-mono text-[11px] uppercase tracking-widest text-zinc-500 dark:text-zinc-400">
								Newsletter
							</span>
						</div>
						<h3 className="mt-1 text-base font-semibold text-zinc-900 dark:text-white">
							{title}
						</h3>
						<p className="mt-1 text-xs leading-relaxed text-zinc-600 dark:text-zinc-400">
							{description}
						</p>
					</div>
					<div className="w-full lg:max-w-md">{result}</div>
				</div>
				{errorMessage && !isSuccess && (
					<p className="mt-1.5 font-mono text-[11px] text-rose-600 dark:text-rose-400">
						{errorMessage}
					</p>
				)}
			</div>
		);
	}

	return (
		<div
			className={`rounded border border-dashed border-zinc-300 bg-zinc-50/70 p-6 dark:border-zinc-800 dark:bg-zinc-950/60 sm:p-8 ${className}`}
		>
			<div className="max-w-xl">
				<span className="font-mono text-[11px] uppercase tracking-widest text-zinc-500 dark:text-zinc-400">
					Newsletter
				</span>
				<h3 className="mt-1 text-lg font-semibold text-zinc-900 dark:text-white">
					{title}
				</h3>
				<p className="mt-2 text-xs leading-relaxed text-zinc-600 dark:text-zinc-400">
					{description}
				</p>
			</div>
			<div className="mt-6">{result}</div>
			{errorMessage && !isSuccess && (
				<p className="mt-2 font-mono text-[11px] text-rose-600 dark:text-rose-400">
					{errorMessage}
				</p>
			)}
		</div>
	);
}

// apps/docs/.vitepress/theme/components/NewsletterSignup.vue
<script setup lang="ts">
import { ref } from "vue";

/**
 * Newsletter signup for the docs site.
 *
 * The docs site is a static VitePress build. Resend has no browser-safe API
 * key, so the form POSTs to a same-origin Cloudflare Pages Function
 * (`/api/subscribe`) that holds the secret `RESEND_API_KEY` server-side and
 * forwards the contact to Resend, adding it to the "Docs newsletter" segment.
 * The secret never reaches the browser.
 *
 * @see apps/docs/functions/api/subscribe.ts — the server-side proxy.
 */

const SUBSCRIBE_ENDPOINT = "/api/subscribe";

withDefaults(
	defineProps<{
		/** Source label — accepted for caller compatibility; the segment is applied server-side. */
		event?: string;
		/** Headline above the form. */
		title?: string;
		/** Supporting line under the headline. */
		description?: string;
	}>(),
	{
		event: "blog",
		title: "Stay in the loop",
		description:
			"New posts, changelog highlights, and the occasional deep dive — straight to your inbox. No spam.",
	},
);

type Status = "idle" | "submitting" | "success" | "error";

const email = ref("");
const status = ref<Status>("idle");
const errorMessage = ref("");

/** Pragmatic email shape check — the real validation runs server-side. */
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

async function handleSubmit() {
	if (status.value === "submitting") return;

	const value = email.value.trim();
	if (!EMAIL_RE.test(value)) {
		status.value = "error";
		errorMessage.value = "Please enter a valid email address.";
		return;
	}

	status.value = "submitting";
	errorMessage.value = "";

	try {
		const response = await fetch(SUBSCRIBE_ENDPOINT, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ email: value }),
		});

		// Parse body even on error for actionable message.
		let data: { ok?: boolean; error?: string } | null = null;
		try {
			data = (await response.json()) as { ok?: boolean; error?: string };
		} catch {
			// non-JSON — will be handled by ok check
		}

		if (!response.ok || (data && data.error)) {
			throw new Error(data?.error || `Subscribe failed (${response.status})`);
		}

		status.value = "success";
		email.value = "";
	} catch (err) {
		status.value = "error";
		errorMessage.value =
			err instanceof Error && err.message
				? err.message
				: "Something went wrong. Please try again.";
	}
}
</script>

<template>
  <section class="newsletter">
    <div class="newsletter-body">
      <h3 class="newsletter-title">{{ title }}</h3>
      <p class="newsletter-description">{{ description }}</p>

      <form
        v-if="status !== 'success'"
        class="newsletter-form"
        @submit.prevent="handleSubmit"
      >
        <input
          v-model="email"
          type="email"
          class="newsletter-input"
          placeholder="you@example.com"
          autocomplete="email"
          aria-label="Email address"
          :disabled="status === 'submitting'"
          required
        />
        <button
          type="submit"
          class="newsletter-button"
          :disabled="status === 'submitting'"
        >
          {{ status === "submitting" ? "Subscribing…" : "Subscribe" }}
        </button>
      </form>

      <p v-if="status === 'success'" class="newsletter-note success">
        ✓ You're in. Welcome email on its way.
      </p>
      <p v-else-if="status === 'error'" class="newsletter-note error">
        {{ errorMessage }}
      </p>
    </div>
  </section>
</template>

<style scoped>
.newsletter {
  margin: 20px 0;
  padding: 20px;
  border: 1px solid var(--vp-c-divider);
  border-radius: var(--tek-radius);
  background: var(--vp-c-bg-soft);
  box-shadow: var(--tek-shadow-sm);
}

.newsletter-title {
  font-family: var(--vp-font-family-display);
  font-size: 20px;
  font-weight: 700;
  line-height: 1.25;
  letter-spacing: -0.01em;
  color: var(--vp-c-text-1);
  margin: 0 0 8px;
}

.newsletter-description {
  font-size: 14px;
  line-height: 1.6;
  color: var(--vp-c-text-2);
  margin: 0 0 18px;
}

.newsletter-form {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}

.newsletter-input {
  flex: 1;
  min-width: 220px;
  padding: 8px 12px;
  font-size: 14px;
  color: var(--vp-c-text-1);
  background: var(--vp-c-bg);
  border: 1px solid var(--vp-c-border);
  border-radius: var(--tek-radius);
  transition: border-color 0.2s, box-shadow 0.2s;
}

.newsletter-input:focus {
  outline: none;
  border-color: var(--vp-c-brand-1);
  box-shadow: 0 0 0 3px var(--vp-c-brand-soft);
}

.newsletter-input:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.newsletter-button {
  flex-shrink: 0;
  padding: 10px 22px;
  font-family: var(--vp-font-family-display);
  font-size: 14px;
  font-weight: 600;
  color: var(--vp-c-bg);
  background: var(--vp-c-brand-1);
  border: none;
  border-radius: var(--tek-radius);
  cursor: pointer;
  box-shadow: var(--tek-shadow-md);
  transition: transform 0.2s, box-shadow 0.2s, opacity 0.2s;
}

.newsletter-button:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: var(--tek-shadow-glow);
}

.newsletter-button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.newsletter-note {
  margin: 14px 0 0;
  font-family: var(--vp-font-family-mono);
  font-size: 13px;
  color: var(--vp-c-text-3);
}

.newsletter-note.success {
  color: var(--vp-c-brand-1);
  font-weight: 600;
}

.newsletter-note.error {
  color: var(--vp-c-danger-1, #e5484d);
}

@media (max-width: 640px) {
  .newsletter {
    padding: 24px 20px;
  }

  .newsletter-button {
    width: 100%;
  }
}
</style>
