// apps/docs/.vitepress/theme/components/CookbookIndex.vue
<script setup>
import { ref, computed } from 'vue'
import { Icon } from '@iconify/vue'
import { data as cookbooks } from '../cookbooks.data.ts'
import { withBase } from 'vitepress'

const searchQuery = ref('')
const selectedCategory = ref('all')

const categories = [
  { id: 'all', name: 'All' },
  { id: 'cli', name: 'Apps & CLI' },
  { id: 'connectors', name: 'Connectors' },
  { id: 'mcp', name: 'MCP & Cloud' }
]

const getRecipeCategory = (recipe) => {
  const url = (recipe.url || '').toLowerCase()
  const title = (recipe.frontmatter?.title || '').toLowerCase()
  if (url.includes('connector') || title.includes('connector') || title.includes('github') || title.includes('notion') || title.includes('linear')) {
    return 'connectors'
  }
  if (url.includes('mcp') || url.includes('sync') || url.includes('hosted') || title.includes('mcp') || title.includes('sync')) {
    return 'mcp'
  }
  return 'cli'
}

const isComingSoon = (recipe) => recipe.frontmatter?.status === 'coming-soon'

const filteredCookbooks = computed(() => {
  return cookbooks
    .filter(item => {
      const matchesCat = selectedCategory.value === 'all' || getRecipeCategory(item) === selectedCategory.value
      if (!matchesCat) return false

      if (!searchQuery.value) return true
      const q = searchQuery.value.toLowerCase()
      return (
        item.frontmatter?.title?.toLowerCase().includes(q) ||
        item.url?.toLowerCase().includes(q)
      )
    })
    // Keep shipped guides ahead of coming-soon stubs within each category.
    .sort((a, b) => Number(isComingSoon(a)) - Number(isComingSoon(b)))
})

const getBrandIconType = (recipe) => {
  const url = (recipe.url || '').toLowerCase()
  const title = (recipe.frontmatter?.title || '').toLowerCase()
  const combined = url + ' ' + title

  if (combined.includes('aider')) return 'aider'
  if (combined.includes('amazon')) return 'amazon-q'
  if (combined.includes('antigravity')) return 'antigravity'
  if (combined.includes('claude')) return 'claude'
  if (combined.includes('cline')) return 'cline'
  if (combined.includes('codex')) return 'codex'
  if (combined.includes('command')) return 'command-code'
  if (combined.includes('copilot')) return 'copilot'
  if (combined.includes('cursor')) return 'cursor'
  if (combined.includes('gemini')) return 'gemini'
  if (combined.includes('github')) return 'github'
  if (combined.includes('jetbrains')) return 'jetbrains'
  if (combined.includes('kilo')) return 'kilo-code'
  if (combined.includes('linear')) return 'linear'
  if (combined.includes('notion')) return 'notion'
  if (combined.includes('opencode')) return 'opencode'
  if (combined.includes('vercel')) return 'vercel'
  if (combined.includes('windsurf')) return 'windsurf'
  if (combined.includes('zed')) return 'zed'
  return 'memofs'
}

const brandMap = {
  'aider': { name: 'Aider', icon: 'simple-icons:python' },
  'amazon-q': { name: 'Amazon Q', icon: 'simple-icons:amazonaws' },
  'antigravity': { name: 'Google Antigravity', icon: 'logos:google-icon' },
  'claude': { name: 'Claude Code', icon: 'simple-icons:anthropic' },
  'cline': { name: 'Cline', icon: 'ph:robot-bold' },
  'codex': { name: 'Codex', icon: 'simple-icons:openai' },
  'command-code': { name: 'Command Code', icon: 'ph:terminal-window-bold' },
  'copilot': { name: 'GitHub Copilot', icon: 'simple-icons:githubcopilot' },
  'cursor': { name: 'Cursor', icon: 'simple-icons:cursor' },
  'gemini': { name: 'Gemini CLI', icon: 'simple-icons:googlegemini' },
  'github': { name: 'GitHub', icon: 'simple-icons:github' },
  'jetbrains': { name: 'JetBrains AI', icon: 'simple-icons:jetbrains' },
  'kilo-code': { name: 'Kilo Code', icon: 'ph:lightning-bold' },
  'linear': { name: 'Linear', icon: 'simple-icons:linear' },
  'notion': { name: 'Notion', icon: 'simple-icons:notion' },
  'opencode': { name: 'OpenCode', icon: 'ph:code-bold' },
  'vercel': { name: 'Vercel AI SDK', icon: 'simple-icons:vercel' },
  'windsurf': { name: 'Windsurf', icon: 'simple-icons:codeium' },
  'zed': { name: 'Zed AI', icon: 'simple-icons:zeddotdev' },
  'memofs': { name: 'MemoFS', icon: 'ph:brain-bold' },

}

const getBrandInfo = (recipe) => {
  const type = getBrandIconType(recipe)
  return brandMap[type] || brandMap['memofs']
}
</script>

<template>
  <div class="cookbook-page">
    <div class="cookbook-container">
      <!-- Header -->
      <div class="cookbook-header">
        <span class="cookbook-kicker">Recipes</span>
        <h1 class="cookbook-title">Cookbooks</h1>
        <p class="cookbook-subtitle">
          Step-by-step tutorials for installing, configuring, and using MemoFS.
        </p>
      </div>

      <!-- Controls (Categories + Search) -->
      <div class="cookbook-controls">
        <div class="cookbook-category-pills">
          <button 
            v-for="cat in categories" 
            :key="cat.id"
            class="pill-btn"
            :class="{ active: selectedCategory === cat.id }"
            @click="selectedCategory = cat.id"
          >
            {{ cat.name }}
          </button>
        </div>

        <div class="cookbook-search-box">
          <svg class="search-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <input 
            v-model="searchQuery"
            type="text" 
            placeholder="Search cookbooks..." 
            class="search-field"
          />
        </div>
      </div>

      <!-- Grid of Cards (3 per row on desktop, without description) -->
      <div v-if="filteredCookbooks.length > 0" class="cookbook-grid">
        <a
          v-for="recipe in filteredCookbooks" 
          :key="recipe.url"
          :href="withBase(recipe.url)"
          :class="['cookbook-card', { 'is-coming-soon': isComingSoon(recipe) }]"
        >
          <span v-if="isComingSoon(recipe)" class="coming-soon-ribbon">Coming Soon</span>

          <div class="card-main-content">
            <div class="card-meta">
              <span class="meta-label">How-To Guide</span>
              <template v-if="recipe.frontmatter?.estimatedMinutes">
                <span class="meta-dot">•</span>
                <span class="meta-time">{{ recipe.frontmatter.estimatedMinutes }} min read</span>
              </template>
            </div>

            <h2 class="card-title">
              {{ recipe.frontmatter?.title }}
            </h2>
          </div>

          <div class="card-footer">
            <!-- Brand Icon -->
            <div class="brand-badge">
              <svg v-if="getBrandIconType(recipe) === 'memofs'" class="icon-svg" viewBox="0 0 100 100">
                <polygon fill="#4cae61" points="50,82 12,62 50,45 88,62" />
                <polygon fill="#2c9ab8" points="50,63 12,43 50,26 88,43" />
                <polygon fill="#258acb" points="50,45 12,25 50,8 88,25" />
                <circle fill="#ffffff" cx="50" cy="23" r="3.5" />
                <circle fill="#ffffff" cx="35" cy="30" r="1.5" opacity="0.6" />
                <circle fill="#ffffff" cx="65" cy="30" r="1.5" opacity="0.6" />
                <circle fill="#ffffff" cx="50" cy="37" r="1.5" opacity="0.6" />
              </svg>
              <Icon v-else :icon="getBrandInfo(recipe).icon" class="icon-svg" />
              <span>{{ getBrandInfo(recipe).name }}</span>
            </div>

            <span class="read-link">
              {{ isComingSoon(recipe) ? 'Preview' : 'Read Guide' }} &rarr;
            </span>
          </div>
        </a>
      </div>

      <!-- Empty State -->
      <div v-else class="empty-state">
        <svg class="empty-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
        </svg>
        <h3 class="empty-title">No cookbooks found</h3>
        <p class="empty-desc">We couldn't find any cookbooks matching your search query.</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.cookbook-page {
  width: 100%;
  padding: 48px 0 96px;
}

.cookbook-container {
  max-width: var(--tek-container, 1200px);
  margin: 0 auto;
  padding: 0 24px;
}

.cookbook-header {
  margin-bottom: 36px;
}

.cookbook-kicker {
  display: inline-block;
  font-family: var(--vp-font-family-mono);
  font-size: 12px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.14em;
  color: var(--vp-c-brand-1);
}

.cookbook-title {
  font-family: var(--vp-font-family-display);
  font-size: clamp(32px, 5vw, 44px);
  font-weight: 800;
  letter-spacing: -0.02em;
  color: var(--vp-c-text-1);
  margin-top: 6px;
  line-height: 1.1;
}

.cookbook-subtitle {
  font-size: 16px;
  color: var(--vp-c-text-2);
  margin-top: 12px;
  max-width: 640px;
  line-height: 1.6;
}

.cookbook-controls {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 40px;
}

.cookbook-category-pills {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.pill-btn {
  border-radius: 6px;
  padding: 6px 14px;
  font-size: 12px;
  font-weight: 700;
  background: var(--vp-c-bg-soft);
  border: 1px solid var(--vp-c-divider);
  color: var(--vp-c-text-2);
  cursor: pointer;
  transition: all 0.2s ease;
}

.pill-btn:hover {
  background: var(--vp-c-bg-mute);
  color: var(--vp-c-text-1);
}

.pill-btn.active {
  background: var(--vp-c-brand-soft);
  border-color: var(--vp-c-brand-1);
  color: var(--vp-c-brand-1);
}

.cookbook-search-box {
  position: relative;
  width: 100%;
  max-width: 320px;
}

.search-icon {
  position: absolute;
  left: 12px;
  top: 50%;
  transform: translateY(-50%);
  width: 16px;
  height: 16px;
  color: var(--vp-c-text-3);
  pointer-events: none;
}

.search-field {
  display: block;
  width: 100%;
  border-radius: 8px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg-soft);
  padding: 8px 16px 8px 36px;
  font-size: 14px;
  color: var(--vp-c-text-1);
  outline: none;
  transition: all 0.2s ease;
}

.search-field:focus {
  border-color: var(--vp-c-brand-1);
  background: var(--vp-c-bg);
  box-shadow: 0 0 0 2px var(--vp-c-brand-soft);
}

.cookbook-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 24px;
}

@media (max-width: 960px) {
  .cookbook-grid {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 640px) {
  .cookbook-grid {
    grid-template-columns: 1fr;
  }
}

.cookbook-card {
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  border-radius: 6px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg-soft);
  padding: 24px;
  text-decoration: none !important;
  transition: all 0.3s ease;
  height: 100%;
}

.cookbook-card:hover {
  border-color: var(--vp-c-brand-1);
  background: var(--vp-c-bg-alt);
  box-shadow: 0 12px 32px -8px rgba(0, 0, 0, 0.25);
  transform: translateY(-2px);
}

.cookbook-card.is-coming-soon {
  opacity: 0.72;
  border-style: dashed;
}

.cookbook-card.is-coming-soon:hover {
  opacity: 1;
}

.coming-soon-ribbon {
  position: absolute;
  top: 14px;
  right: 14px;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: #92400e;
  background: #fef3c7;
  border: 1px solid #fcd34d;
  border-radius: 999px;
  padding: 3px 9px;
}

.dark .coming-soon-ribbon {
  color: #fde68a;
  background: rgba(146, 64, 14, 0.35);
  border-color: rgba(252, 211, 77, 0.5);
}

.card-main-content {
  display: flex;
  flex-direction: column;
}

.card-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  font-weight: 600;
  color: var(--vp-c-brand-1);
  margin-bottom: 12px;
}

.meta-label {
  font-weight: 700;
}

.meta-dot {
  color: var(--vp-c-text-3);
}

.meta-time {
  color: var(--vp-c-text-2);
}

.card-title {
  font-family: var(--vp-font-family-display);
  font-size: 19px;
  font-weight: 700;
  color: var(--vp-c-text-1);
  line-height: 1.35;
  margin-bottom: 0;
  transition: color 0.2s ease;
}

.cookbook-card:hover .card-title {
  color: var(--vp-c-brand-1);
}

.card-footer {
  margin-top: 32px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-top: 1px solid var(--vp-c-divider);
  padding-top: 16px;
}

.brand-badge {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  font-weight: 600;
  color: var(--vp-c-text-2);
}

.icon-svg {
  width: 16px;
  height: 16px;
}

.read-link {
  font-size: 12px;
  font-weight: 700;
  color: var(--vp-c-brand-1);
}

.cookbook-card:hover .read-link {
  text-decoration: underline;
}

.empty-state {
  padding: 64px 24px;
  text-align: center;
  border: 1px dashed var(--vp-c-divider);
  border-radius: 6px;
  grid-column: 1 / -1;
}

.empty-icon {
  width: 48px;
  height: 48px;
  margin: 0 auto;
  color: var(--vp-c-text-3);
}

.empty-title {
  margin-top: 16px;
  font-size: 18px;
  font-weight: 700;
  color: var(--vp-c-text-1);
}

.empty-desc {
  margin-top: 4px;
  font-size: 14px;
  color: var(--vp-c-text-2);
}
</style>

// apps/docs/app/components/cookbook-index.tsx
import { useMemo, useState } from "react";
import { Link } from "react-router";
import { source } from "~/lib/source";

interface Category {
	id: string;
	name: string;
}

const CATEGORIES: Category[] = [
	{ id: "all", name: "All Recipes" },
	{ id: "agents", name: "Coding Agents & IDEs" },
	{ id: "connectors", name: "Connectors" },
	{ id: "frameworks", name: "Frameworks & MCP" },
];

function getRecipeCategory(url: string, title: string): string {
	const u = url.toLowerCase();
	const t = title.toLowerCase();

	if (
		u.includes("connector") ||
		t.includes("connector") ||
		u.includes("github") ||
		u.includes("linear") ||
		u.includes("notion")
	) {
		return "connectors";
	}

	if (
		u.includes("ai-sdk") ||
		u.includes("mcp") ||
		u.includes("hosted") ||
		u.includes("intelligence") ||
		u.includes("memory-intelligence") ||
		u.includes("sync") ||
		u.includes("rollback") ||
		u.includes("org-core") ||
		u.includes("webhooks")
	) {
		return "frameworks";
	}

	return "agents";
}

function getBrandName(slug: string, title: string): string {
	const map: Record<string, string> = {
		"claude-code": "Claude Code",
		cursor: "Cursor",
		codex: "OpenAI Codex",
		copilot: "GitHub Copilot",
		cline: "Cline",
		aider: "Aider",
		antigravity: "Antigravity",
		gemini: "Google Gemini",
		windsurf: "Windsurf",
		opencode: "OpenCode",
		"kilo-code": "Kilo Code",
		jetbrains: "JetBrains",
		"amazon-q": "Amazon Q",
		zed: "Zed",
		"command-code": "Command Code",
		"ai-sdk": "Vercel AI SDK",
		"github-connector": "GitHub",
		"linear-connector": "Linear",
		"notion-connector": "Notion",
		"gh-pr-summaries": "GitHub Actions",
		"hosted-mcp": "Hosted MCP",
		"memory-intelligence": "Memory Intelligence",
		"org-core-memory": "Enterprise Core",
		rollback: "Memory Rollback",
		sync: "Cloud Sync",
		webhooks: "Webhooks",
	};

	return (
		map[slug] || title.replace(/^How to (use|connect) MemoFS (with|to) /i, "")
	);
}

function BrandIcon({ slug }: { slug: string }) {
	// SVG mini brand indicators
	if (slug === "claude-code") {
		return (
			<span className="flex size-4 items-center justify-center rounded-full bg-amber-500/10 text-[10px] font-bold text-amber-600 dark:text-amber-400">
				C
			</span>
		);
	}
	if (slug === "cursor") {
		return (
			<span className="flex size-4 items-center justify-center rounded-full bg-zinc-900 text-[10px] font-bold text-white dark:bg-white dark:text-black">
				▲
			</span>
		);
	}
	if (
		slug === "copilot" ||
		slug === "github-connector" ||
		slug === "gh-pr-summaries"
	) {
		return (
			<span className="flex size-4 items-center justify-center rounded-full bg-zinc-800 text-[10px] font-bold text-white dark:bg-zinc-200 dark:text-black">
				⌥
			</span>
		);
	}
	if (slug === "linear-connector") {
		return (
			<span className="flex size-4 items-center justify-center rounded-full bg-indigo-500/10 text-[10px] font-bold text-indigo-600 dark:text-indigo-400">
				L
			</span>
		);
	}
	if (slug === "notion-connector") {
		return (
			<span className="flex size-4 items-center justify-center rounded-full bg-zinc-100 text-[10px] font-bold text-zinc-800 dark:bg-zinc-800 dark:text-white">
				N
			</span>
		);
	}
	if (slug === "gemini" || slug === "antigravity") {
		return (
			<span className="flex size-4 items-center justify-center rounded-full bg-blue-500/10 text-[10px] font-bold text-blue-600 dark:text-blue-400">
				G
			</span>
		);
	}
	return (
		<span className="flex size-4 items-center justify-center rounded-full bg-zinc-100 text-[10px] font-bold text-zinc-600 dark:bg-zinc-800 dark:text-zinc-400">
			◈
		</span>
	);
}

export function CookbookIndex() {
	const [searchQuery, setSearchQuery] = useState("");
	const [selectedCategory, setSelectedCategory] = useState("all");

	// Get all cookbook recipe pages from source
	const recipes = useMemo(() => {
		return source
			.getPages()
			.filter(
				(p) =>
					p.url.startsWith("/docs/cookbooks/") &&
					p.url !== "/docs/cookbooks" &&
					p.url !== "/docs/cookbooks/index",
			)
			.map((p) => {
				const slug = p.slugs[p.slugs.length - 1] || "";
				const title = p.data.title || slug;
				const category = getRecipeCategory(p.url, title);
				const extra = p.data as unknown as Record<string, unknown>;
				const isComingSoon = extra.status === "coming-soon";
				const estimatedMinutes =
					typeof extra.estimatedMinutes === "number" ||
					typeof extra.estimatedMinutes === "string"
						? String(extra.estimatedMinutes)
						: String(Math.max(2, Math.min(8, Math.round(title.length / 10))));

				return {
					url: p.url,
					slug,
					title,
					description: p.data.description,
					category,
					brand: getBrandName(slug, title),
					isComingSoon,
					estimatedMinutes,
				};
			})
			.sort((a, b) => {
				if (a.isComingSoon !== b.isComingSoon) {
					return a.isComingSoon ? 1 : -1;
				}
				return a.title.localeCompare(b.title);
			});
	}, []);

	// Category counts
	const categoryCounts = useMemo(() => {
		const counts: Record<string, number> = { all: recipes.length };
		for (const r of recipes) {
			counts[r.category] = (counts[r.category] || 0) + 1;
		}
		return counts;
	}, [recipes]);

	// Filtered list based on search and category
	const filtered = useMemo(() => {
		const query = searchQuery.trim().toLowerCase();
		return recipes.filter((r) => {
			const matchesCategory =
				selectedCategory === "all" || r.category === selectedCategory;
			if (!matchesCategory) return false;

			if (!query) return true;
			return (
				r.title.toLowerCase().includes(query) ||
				r.brand.toLowerCase().includes(query) ||
				(r.description?.toLowerCase().includes(query) ?? false) ||
				r.slug.toLowerCase().includes(query)
			);
		});
	}, [recipes, searchQuery, selectedCategory]);

	return (
		<div className="not-prose w-full space-y-8">
			{/* Filter Controls: Category Pills + Search Bar */}
			<div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between border-b border-dashed border-zinc-200 dark:border-zinc-800/80 pb-6">
				{/* Category Pills with counts */}
				<div className="flex flex-wrap items-center gap-2">
					{CATEGORIES.map((cat) => {
						const isActive = selectedCategory === cat.id;
						const count = categoryCounts[cat.id] || 0;
						return (
							<button
								key={cat.id}
								type="button"
								onClick={() => setSelectedCategory(cat.id)}
								className={`inline-flex items-center gap-1.5 cursor-pointer rounded border px-3 py-1.5 text-xs font-semibold transition-all ${
									isActive
										? "border-zinc-900 bg-zinc-900 text-white dark:border-white dark:bg-white dark:text-black shadow-sm"
										: "border-zinc-200 bg-zinc-50 text-zinc-600 hover:border-zinc-300 hover:bg-zinc-100 dark:border-zinc-800 dark:bg-zinc-900/90 dark:text-zinc-400 dark:hover:border-zinc-700 dark:hover:bg-zinc-800/80 dark:hover:text-zinc-200"
								}`}
							>
								<span>{cat.name}</span>
								<span
									className={`rounded px-1.5 py-0.2 font-mono text-[10px] ${
										isActive
											? "bg-zinc-800 text-zinc-200 dark:bg-zinc-200 dark:text-zinc-800"
											: "bg-zinc-200/80 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-400"
									}`}
								>
									{count}
								</span>
							</button>
						);
					})}
				</div>

				{/* Search Field */}
				<div className="relative w-full sm:w-72">
					<input
						type="text"
						value={searchQuery}
						onChange={(e) => setSearchQuery(e.target.value)}
						placeholder="Search by agent, IDE, or tool..."
						className="w-full rounded border border-zinc-200 bg-white px-3 py-1.5 pl-8 text-xs text-zinc-900 outline-none transition-colors placeholder:text-zinc-400 focus:border-zinc-900 dark:border-zinc-800 dark:bg-zinc-950 dark:text-white dark:placeholder:text-zinc-500 dark:focus:border-zinc-600"
					/>
					<svg
						className="pointer-events-none absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-zinc-400 dark:text-zinc-500"
						fill="none"
						viewBox="0 0 24 24"
						stroke="currentColor"
						strokeWidth={2}
					>
						<title>Search</title>
						<path
							strokeLinecap="round"
							strokeLinejoin="round"
							d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
						/>
					</svg>
				</div>
			</div>

			{/* Recipe Cards Grid (3 per row on desktop) */}
			{filtered.length > 0 ? (
				<div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
					{filtered.map((recipe) => (
						<Link
							key={recipe.url}
							to={recipe.url}
							className={`group relative flex flex-col justify-between rounded-lg border border-dashed p-6 transition-all duration-200 hover:-translate-y-1 ${
								recipe.isComingSoon
									? "border-zinc-300/70 bg-zinc-50/40 opacity-75 hover:opacity-100 dark:border-zinc-800/70 dark:bg-zinc-950/30"
									: "border-zinc-200 bg-white hover:border-zinc-400 hover:shadow-md dark:border-zinc-800 dark:bg-zinc-950/70 dark:hover:border-zinc-600"
							}`}
						>
							{recipe.isComingSoon && (
								<span className="absolute right-3.5 top-3.5 rounded-full border border-amber-300 bg-amber-50 px-2 py-0.5 font-mono text-[9px] font-bold uppercase tracking-wider text-amber-800 dark:border-amber-900/60 dark:bg-amber-950/40 dark:text-amber-300">
									Coming Soon
								</span>
							)}

							<div>
								{/* Header / Meta */}
								<div className="flex items-center gap-2 font-mono text-[10px] text-zinc-500 dark:text-zinc-400">
									<span className="font-semibold uppercase tracking-wider text-zinc-600 dark:text-zinc-300">
										How-To Guide
									</span>
									<span>·</span>
									<span>{recipe.estimatedMinutes} min read</span>
								</div>

								{/* Card Title */}
								<h3 className="mt-3 text-base font-bold leading-snug text-zinc-900 group-hover:text-black dark:text-zinc-100 dark:group-hover:text-white transition-colors">
									{recipe.title}
								</h3>

								{/* Description */}
								{recipe.description && (
									<p className="mt-2 line-clamp-2 text-xs leading-relaxed text-zinc-500 dark:text-zinc-400 font-normal">
										{recipe.description}
									</p>
								)}
							</div>

							{/* Card Footer */}
							<div className="mt-6 flex items-center justify-between border-t border-dashed border-zinc-100 dark:border-zinc-800/80 pt-4 text-xs">
								<div className="flex items-center gap-2 font-medium text-zinc-700 dark:text-zinc-300">
									<BrandIcon slug={recipe.slug} />
									<span>{recipe.brand}</span>
								</div>
								<span className="inline-flex items-center font-semibold text-zinc-600 group-hover:text-zinc-900 dark:text-zinc-400 dark:group-hover:text-white transition-colors">
									{recipe.isComingSoon ? "Preview" : "Read Guide"}
									<span className="ml-1 transition-transform group-hover:translate-x-1">
										→
									</span>
								</span>
							</div>
						</Link>
					))}
				</div>
			) : (
				<div className="rounded-lg border border-dashed border-zinc-200 p-16 text-center dark:border-zinc-800">
					<p className="text-sm font-semibold text-zinc-800 dark:text-zinc-200">
						No cookbooks found matching "{searchQuery}"
					</p>
					<p className="mt-1 text-xs text-zinc-500">
						Try adjusting your search query or selecting a different category.
					</p>
				</div>
			)}
		</div>
	);
}
